# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14vE62a4FYuBlN_vRC_CM6j_7FoJPFaPY
"""

# !pip install gradio,opencv_python

import cv2
import gradio as gr
def upscale(image,scale_factor):
    image=cv2.cvtColor(image,cv2.COLOR_RGB2BGR)
    height,width=image.shape[:2]
    new_dim=(int(height*scale_factor),int(width*scale_factor))
    up_scaled=cv2.cvtColor(image,cv2.COLOR_BGR2RGB)
    return up_scaled
gr.Interface(upscale,inputs=[gr.Image(type="numpy"),gr.Slider(1.0,4.0,step=0.1,label="scale_factor")],outputs=gr.Image(type="numpy")).launch()
