name: Test and Deploy to Hub

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # Job 1: Run all the tests
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov
          
      - name: Run tests with coverage
        run: |
          python -m pytest tests/test_app.py -v --cov=. --cov-report=xml --cov-report=html --disable-warnings

      - name: Upload coverage reports as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            coverage.xml
            htmlcov/

  # Job 2: Deploy to Hugging Face
  sync-to-hub:
    runs-on: ubuntu-latest
    needs: test

    if: github.event_name == 'push' && github.ref == 'refs/heads/main' 
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
          
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push https://KeerthiVM:$HF_TOKEN@huggingface.co/spaces/SkinCancerDiagnosis/Image_Upscaling main --force


  notify_slack_on_success:
    runs-on: ubuntu-latest
    needs: [test, sync-to-hub] 
    if: success()             
    steps:
      - name: Send Slack notification on success
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_SECRET }}
          SLACK_COLOR: 'good' 
          SLACK_TITLE: 'Build Successfully Passed & Deployed for Image Upscaling task!'
          SLACK_MESSAGE: 'Build for `${{ github.repository }}` passed. Commit by @${{ github.actor }}.'
          SLACK_FOOTER: 'Changes: ${{ github.event.head_commit.message }}'

  notify_slack_on_failure:
    runs-on: ubuntu-latest
    needs: test              
    if: failure()           
    steps:
      - name: Send Slack notification on failure
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_SECRET }}
          SLACK_COLOR: 'danger' 
          SLACK_TITLE: 'Build FAILED for Image Upscaling task!'
          SLACK_MESSAGE: '<!here> Build for `${{ github.repository }}` failed. Commit by @${{ github.actor }}. Deployment was skipped.'
          SLACK_FOOTER: '<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Click to View Failed Run>'
